services:
  adguardhome:
    container_name: adguardhome-a
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    ports:
      - 3053:53/tcp
      - 3053:53/udp
      - 2067:67/udp
      - 2068:68/udp
      - 2080:80/tcp
      - 29443:443/tcp
      - 29443:443/udp
      - 23069:3000/tcp
      - 2853:853/tcp
      - 2784:784/udp
      - 2853:853/udp
      - 28853:8853/udp
      - 25443:5443/tcp
      - 25443:5443/udp
    image: adguard/adguardhome
    networks:
      - traefik
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
networks:
  traefik:
    external: true
