services:
  smartdns:
    container_name: smartdns-a
    restart: always
    ports:
      - 5353:5353/udp
    volumes:
      - ./smartdns:/etc/smartdns
      - ./cache:/etc/smartdns/cache
    logging:
      driver: json-file
      options:
        max-size: 10m  
    image: pymumu/smartdns:latest
